version: "3.9"

services:
  postgresql:
    container_name: scrapper_db
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scrapper
    volumes:
      - scrapper_db_data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=testdb
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  scrapper_db_data:
    name: scrapper_db_data
  rabbitmq_data:
    name: rabbitmq_data

networks:
  backend:
    driver: bridge