name: build-bot

on:
  push:
    paths:
      - '.github/workflows/bot.yml'
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Maven package bot
        run: mvn package -pl bot -am

      - name: Build Docker Image
        run: docker build bot -t image-bot