name: build-scrapper

on:
  push:
    paths:
      - '.github/workflows/scrapper.yml'
      - 'scraper/**'
      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Maven package scrapper
        run: mvn package -pl scrapper -am

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false